version: '3'
services:
  redis:
    image: 'redis:alpine'
    command: 'redis-server --appendonly yes'
    ports:
      - '6379:6379'
  flask:
    build: .
    command: 'python app.py'
    restart: always
    volumes:
      - .:/code
    ports:
      - '5000:5000'
  celery:
    build: .
    command: 'celery -A app.celery worker --loglevel=info'